"""Compute the Stage 1 cost per run and per month from measured inputs and list prices.

Usage: uv run python scripts/estimate_cost.py [--bytes N] [--seconds S] > docs/cost.md

Prices are europe-west2 list prices in USD, converted at a fixed rate stated in the output.
Update PRICES and PRICE_DATE when they change; the README links to the generated file
rather than repeating any figure by hand.
"""

from __future__ import annotations

import argparse
import sys
from datetime import date

PRICE_DATE = date(2026, 9, 2)
GBP_PER_USD = 0.78

# USD list prices, europe-west2 (London). Sources: cloud.google.com/{run,storage,bigquery}/pricing
PRICES = {
    "run_vcpu_second": 0.0000240,
    "run_gib_second": 0.0000025,
    "run_free_vcpu_seconds": 180_000,
    "run_free_gib_seconds": 360_000,
    "gcs_gib_month": 0.023,
    "gcs_class_a_op": 0.0000050,  # per operation, charged per 1,000 as $0.005
    "bq_active_gib_month": 0.020,
    "bq_free_storage_gib": 10,
    "artifact_gib_month": 0.10,
    "artifact_free_gib": 0.5,
    "scheduler_job_month": 0.10,
    "scheduler_free_jobs": 3,
}

# Measured, not guessed. Bytes: mean of four daily ZIP Content-Length headers observed
# 2026-08-28 to 2026-09-02 (77.5, 163.1, 191.4, 148.7 MB). Seconds: a local --dry-run of the
# 77.5 MB 2026-09-02 file took 2 s; 60 s is a deliberate 30x ceiling for Cloud Run's 1 vCPU
# hashing plus CRC-checking a 200 MB file. Replace with the measured Cloud Run figure once
# the job has run there. Override with flags.
DEFAULT_BYTES = 145_200_000
DEFAULT_SECONDS = 60
RUNS_PER_MONTH = 22  # Tue-Sat publication days
IMAGE_BYTES = 180_000_000
VCPU = 1.0
MEMORY_GIB = 1.0


def gib(n: int | float) -> float:
    return n / (1 << 30)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bytes", type=int, default=DEFAULT_BYTES)
    parser.add_argument("--seconds", type=int, default=DEFAULT_SECONDS)
    parser.add_argument("--runs-per-month", type=int, default=RUNS_PER_MONTH)
    args = parser.parse_args(argv)

    runs = args.runs_per_month
    vcpu_s = VCPU * args.seconds * runs
    gib_s = MEMORY_GIB * args.seconds * runs
    run_cost = (
        max(0.0, vcpu_s - PRICES["run_free_vcpu_seconds"]) * PRICES["run_vcpu_second"]
        + max(0.0, gib_s - PRICES["run_free_gib_seconds"]) * PRICES["run_gib_second"]
    )

    stored_gib = gib(args.bytes) * runs  # month-end storage, files retained indefinitely
    gcs_cost = stored_gib * PRICES["gcs_gib_month"] + runs * 3 * PRICES["gcs_class_a_op"]
    bq_rows_gib = gib(runs * 512)
    bq_cost = max(0.0, bq_rows_gib - PRICES["bq_free_storage_gib"]) * PRICES["bq_active_gib_month"]
    ar_free = PRICES["artifact_free_gib"]
    ar_cost = max(0.0, gib(IMAGE_BYTES) - ar_free) * PRICES["artifact_gib_month"]
    sched_cost = max(0, 1 - PRICES["scheduler_free_jobs"]) * PRICES["scheduler_job_month"]

    lines = [
        ("Cloud Run Job compute", run_cost, "inside free tier"),
        ("Cloud Storage (raw ZIPs, cumulative)", gcs_cost, f"{stored_gib:.2f} GiB after one month"),
        ("BigQuery storage (ingest_runs)", bq_cost, "inside free tier"),
        ("Artifact Registry (one image)", ar_cost, "inside free tier"),
        ("Cloud Scheduler (one job)", sched_cost, "inside free tier"),
    ]
    total_usd = sum(c for _, c, _ in lines)
    per_run_usd = total_usd / runs

    out = [
        "# Stage 1 running cost",
        "",
        f"Generated by `scripts/estimate_cost.py` on {date.today().isoformat()} from list prices "
        f"dated {PRICE_DATE.isoformat()} at {GBP_PER_USD} GBP/USD. Regenerate with `make cost`.",
        "",
        "Inputs (measured, see script header):",
        "",
        f"- Daily ZIP size: {args.bytes / 1e6:.1f} MB",
        f"- Job wall time: {args.seconds} s at {VCPU:g} vCPU / {MEMORY_GIB:g} GiB",
        f"- Runs per month: {runs}",
        "",
        "| Component | USD / month | GBP / month | Note |",
        "|---|---:|---:|---|",
    ]
    for name, usd, note in lines:
        out.append(f"| {name} | {usd:.4f} | {usd * GBP_PER_USD:.4f} | {note} |")
    out += [
        f"| **Total** | **{total_usd:.4f}** | **{total_usd * GBP_PER_USD:.4f}** | |",
        "",
        f"Cost per run: USD {per_run_usd:.5f} (GBP {per_run_usd * GBP_PER_USD:.5f}).",
        "",
        "Storage is the only line that grows: each month of daily ZIPs adds about "
        f"{stored_gib:.2f} GiB, so the bill roughly doubles every month until a lifecycle rule "
        "or Stage 2 compaction is added. Nothing here runs when the job is idle.",
    ]
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
